### PR TITLE
fix re-generate issue for root dict

### PR DESCRIPTION
**Pull request by fucd**
* remove cmake directory
* re-write CMakeLists.txt
* remove kaldet/ while include header files, because  include_directories changed,

### CODE REVIEW

**Comment by fucd** [comment]
Hi @mirguest
 
I fixed the issue on re-generating root dictionary while each make, based on #23. Can you review it? 

Best,
Chengdong

**Comment by mirguest** [comment]
Hi @fucd ,
Sure, I will have a look and let you know.
Tao

**Comment by mirguest** [comment]
Hi Chengdong,
The compilation is failed as following:
```
[ 14%] Generating genConf/EventSeeder/EventSeederConf.py, genConf/EventSeeder/__init__.py, genConf/EventSeeder/EventSeeder.confdb, genConf/EventSeeder/EventSeeder.confdb2_part
[ 14%] Built target EventSeederConf
[ 14%] Generating ../../../Utilities/KalTest/rootdict/utils.cxx, ../../../Utilities/KalTest/rootdict/utils_rdict.pcm
Error: rootcling: failed to open /tmp/lint/CEPCSW/Utilities/KalTest/rootdict/utils.cxx_tmp_12284 in main
make[2]: *** [../Utilities/KalTest/rootdict/utils.cxx] Error 1
make[1]: *** [Utilities/KalTest/CMakeFiles/KalTestLib.dir/all] Error 2
make: *** [all] Error 2
```

Could you checkout the new code and have a fresh new build?

Tao

**Comment by fucd** [comment]
Hi @mirguest

It seems missing a sentence to mkdir, I have updated.

Chengdong

**Review by mirguest — APPROVED** [review]

**Pull request merged**
