### PR TITLE
CRD geometry implementation and option 

### PR DESCRIPTION
**Pull request by fucd**
* Modification on construction
     * DriftChamber: change global volume to envelope defined in compact file, in order to easy to insert silicon layer between inner and outer chambers
      `<envelope vis="SeeThrough">
        <shape type="BooleanShape" operation="Union" material="Air">
          <shape type="Tube" rmin="SDT_inner_chamber_radius_min" rmax="SDT_inner_chamber_radius_max" dz="SDT_half_length" />
          <shape type="Tube" rmin="SDT_outer_chamber_radius_min" rmax="SDT_outer_chamber_radius_max" dz="SDT_half_length" />
        </shape>
      </envelope>`
     and add type_flags
`<type_flags type="DetType_TRACKER + DetType_BARREL + DetType_GASEOUS + DetType_WIRE"/>`
    * CRDBeamPipe_v01: first implement for CepC-special beam pipe
* Options
     * first import preliminary version (CRD_o1_v01)  includes beam pipe, VXD, SIT, DC, SET, FTD and Ecal_Crystal
     * CRD_o1_v01/CRD_o1_v01.xml for main compact file
     * CRD_o1_v01/CRD_Dimensions_v01_01.xml for common constants between sub-detectors
     * CRD_common_v01 save option files based on v01_geo construct, CRD_common_v02 will for v02_geo, and so on
     * README: detail description for CRD version
* scripts
     * sim_CRD.py as example to simulate CRD

### CODE REVIEW

**Comment by fucd** [comment]
Hi @mirguest @ihepzhangyao @wenxingfang @LinghuiWuIHEP @xshi 

Can you review this PR#82 for CRD geometry option include DriftChamber and Ecal_Crystal?

Best
Chengdong

**Comment by mirguest** [comment]
Hi @fucd ,
It looks like your PR is not built automatically. Maybe you are blocked by Travis-CI.
Could you send an email to support@travis-ci.com to ask them to check why your PR does not build?
Thank you!
Tao

**Comment by fucd** [comment]
@mirguest Ok, thank you!

**Comment by myliu-hub** [comment]
We tried to detect the above code, and did not find that there is a parameter overlap. At the same time, we ran the script sim_CRD.py to get the visualization of the detector and the position distribution of SIT, SET, FTD, VXD and DC, among them, the producer is muon-, the energy is 100Gev, 2000 cases are simulated, and the location of DC is 200 cases.
b3c6390af355ede491a3af32e689a1b
SIT2000
SET2000
FTD2000
VXD2000
The following figure shows the particle position distribution in DC when the above code is not added.
DC200

**Comment by myliu-hub** [comment]
We tried to detect the above code, and did not find that there is a parameter overlap. At the same time, we ran the script sim_CRD.py to get the visualization of the detector and the position distribution of SIT, SET, FTD, VXD and DC, among them, the producer is muon-, the energy is 100Gev, 2000 cases are simulated, and the location of DC is 200 cases.
b3c6390af355ede491a3af32e689a1b
SIT2000
SET2000
FTD2000
VXD2000
DC200SI
The following figure shows the particle position distribution in DC when the above code is not added.

**Comment by myliu-hub** [comment]
We tried to detect the above code, and did not find that there is a parameter overlap. At the same time, we ran the script sim_CRD.py to get the visualization of the detector and the position distribution of SIT, SET, FTD, VXD and DC, among them, the producer is muon-, the energy is 100Gev, 2000 cases are simulated, and the location of DC is 200 cases.
b3c6390af355ede491a3af32e689a1b
SIT2000
SET2000
FTD2000
VXD2000
DC200SI
The following figure shows the particle position distribution in DC when the above code is not added.
DC200

**Review by mirguest — APPROVED** [review]
@ihepzhangyao and @myliu-hub had reviewed this PR.

**Pull request merged**
