### PR TITLE
Modify Ecal geometry

### PR DESCRIPTION
**Pull request by qwert2333**
Update the crystal Ecal geometry file to: 
  * fix the large memory usage problem for #Issue156
  * group the bars in a super-cell for reconstruction

### CODE REVIEW

**Comment by fucd** [comment]
@qwert2333 Thanks very much. It is very helpful. I just have a minor comment. In current version, the gap is also filled BGO. In my mind, the gap is much possible to place cable, these material maybe is not calculated. On the other hand, extensibility also require. So my suggestion is to set these materials as option in XML.

Chengdong

**Comment by qwert2333** [comment]
Hi @fucd shall we leave these things to the next version? We are still studying the feasibility of this design, it might be a bit early to consider the details like cable, readout, etc. 
New commit is for extension needed by Pandora. I just realized I missed it. 

Thanks!
Fangyi

**Comment by fucd** [comment]
@qwert2333 Sure, I agree to improve it step by step. And the builder seems not work, maybe @mirguest can help.

**Comment by mirguest** [comment]
Hi @qwert2333,
Did you measure the memory usage? Could you show the memory usage? 
Tao

**Comment by qwert2333** [comment]
Hi @mirguest 
Yes I checked with top command, now the memory is ~400M, and previously it is ~1.6G

**Comment by mirguest** [comment]
> Hi @mirguest
> Yes I checked with top command, now the memory is ~400M, and previously it is ~1.6G

That's a good news.

**Review by mirguest — APPROVED** [review]
Looks good. Thanks.
Tao

**Pull request merged**
