### PR TITLE
Add two Endcaps

### PR DESCRIPTION
**Pull request by myliu-hub**

### CODE REVIEW

**Comment by mirguest** [comment]
Hi @fucd and @ihepzhangyao ,

Could you review Mengyao's PR?
Thank you!

Tao

**Comment by fucd** [comment]
@myliu-hub Sorry, I don't know why add the endcap. But from safety, it is better to enlarger the `SDT_half_length`.
And in this PR, new added visible color is fixed as `VisibleRed`. Optional color is suggested. Or to use those default colors set in CRD  will avoid repetition.

Chengdong

**Comment by myliu-hub** [comment]
Hi, @fucd, @mirguest and @ihepzhangyao ,I have modified your suggestion, please review me.

**Comment by myliu-hub** [comment]
Hi, @fucd ， @mirguest  and @ihepzhangyao  ,I have modified your suggestion, please review me，thank you very much!

**Comment by fucd** [comment]
@myliu-hub Thank you for this update. This is my meaning, and people will know the edge of all sub-detectors from CRD_Dimensions_v01_01.xml

Chengdong

**Review by fucd — APPROVED** [review]

**Review by mirguest — APPROVED** [review]

**Pull request merged**
