### PR TITLE
add Interface and tool for dN/dx

### PR DESCRIPTION
**Pull request by wenxingfang**
Add Interface and tool for dN/dx
The GFDndxSimTool is used for dndx sampling based on betagamma value.

### CODE REVIEW

**Comment by wenxingfang** [comment]
Hi @mirguest @ihepzhangyao @LinghuiWuIHEP
I add an Interface and tool for dndx sampling, could you review it ? The specific implementation will be done by @implement
Best,
Wenxing

**Comment by mirguest** [comment]
Hi @wenxingfang ,
Is the dndx interface track level or hit level? Can you make it more clear? Another one is the units are not so clear for me.
Tao

**Comment by wenxingfang** [comment]
Hi @mirguest 

It is for track level. The units for dN/dx I guess is float, but I am not sure, maybe  @LinghuiWuIHEP or @newsubmarine can comment.

Best,
Wenxing

**Comment by mirguest** [comment]
Hi @wenxingfang ,
I don't mean the type, but the units of dN/dx, such as [1/mm] or something else.
This interface is designed in detector simulation framework, so the default units are assumed same as the units in Geant4.
But now, you also use it in the reconstruction part, so it is important to make it clear what the units you are assumed to use.

Tao

**Comment by mirguest** [comment]
Another comment is that it would be a good idea to put some documents at the begining of the file `GFDndxSimTool.h`. 
What does GF mean? Is that Garfield?

**Comment by wenxingfang** [comment]
Hi @mirguest
 
Yes, you are right to make the unit clear, but I don't know the units of dN/dx, I just provided the dummy Interface, it should be specified when one written the real code of the sampling. The GF means "Garfield", it is my arbitrary choice of the name, it can be updated by the tool developer if they have better name.

Best,
Wenxing

**Comment by newsubmarine** [comment]
> Hi @mirguest
> 
> It is for track level. The units for dN/dx I guess is float, but I am not sure, maybe @LinghuiWuIHEP or @newsubmarine can comment.
> 
> Best,
> Wenxing

Hi @mirguest and @wenxingfang 
Technically it is an int quantity for one track. Is that necessary to do conversion ? Since dN/dx is a continuous function of betagamma while sampling . Anyway , that would not change the statistic results, so I think it's ok now.
Conerning to the unit, it is 1/cm , is this the default one in Geant4?

Best,
Shuiting

**Comment by newsubmarine** [comment]
> Another comment is that it would be a good idea to put some documents at the begining of the file `GFDndxSimTool.h`.
> What does GF mean? Is that Garfield?

Thanks all of your effort

> Hi @mirguest
> 
> Yes, you are right to make the unit clear, but I don't know the units of dN/dx, I just provided the dummy Interface, it should be specified when one written the real code of the sampling. The GF means "Garfield", it is my arbitrary choice of the name, it can be updated by the tool developer if they have better name.
> 
> Best,
> Wenxing

Thanks all your effort there, we can devolpe it based on this skeleton, for example the naming, support etc。

**Comment by mirguest** [comment]
Hi @newsubmarine,
Thank you for your reponse. The default unit in Geant4 is mm.
Tao

**Comment by LinghuiWuIHEP** [comment]
> Hi @mirguest
> 
> It is for track level. The units for dN/dx I guess is float, but I am not sure, maybe @LinghuiWuIHEP or @newsubmarine can comment.
> 
> Best,
> Wenxing

Hi @wenxingfang , Yes, the type of dN/dx variable should be float.

Best,
Linghui

**Review by newsubmarine — APPROVED** [review]

**Review by mirguest — APPROVED** [review]
As @newsubmarine approves this PR, I will merge it. Thanks.
Tao

**Pull request merged**
