### PR TITLE
Data: algorithm to dump event infos to TTree format

### PR DESCRIPTION
**Pull request by fucd**
* dump into TTree (ntuple) in root file, and then events can be analysed in ROOT macro. 
* for different collections with same type (such as Track), overload the algorithm like as following:

from Configurables import DumpMCParticleAlg
dumpMC = DumpMCParticleAlg("DumpMC")
dumpMC.MCParticleCollection = "MCParticle"
dumpMC.OutputLevel = DEBUG

from Configurables import DumpTrackAlg
dumpFu = DumpTrackAlg("DumpFu")
dumpFu.TrackCollection = "MarlinTrkTracks"
#dumpFu.OutputLevel = DEBUG                                                                                                                                                                 

dumpCl = DumpTrackAlg("DumpCl")
dumpCl.TrackCollection = "ClupatraTracks"
#dumpCl.OutputLevel = DEBUG                                                                                                                                                                 

dumpSu = DumpTrackAlg("DumpSu")
dumpSu.TrackCollection = "SubsetTracks"
#dumpSu.OutputLevel = DEBUG

### CODE REVIEW

**Comment by fucd** [comment]
@myliu-hub This is an example to read tracks into ROOT TTree branch, and then to analyse performance (such as pull). I hope it is helpful for your work. Can you review it? If possible, it can be merged into CEPCSW.

**Comment by myliu-hub** [comment]
@fucd ,Hi，Thank you very much for your work, but did you not upload the header file?

**Comment by fucd** [comment]
@myliu-hub sorry, it is a mistake. Now I have added the header files.

**Review by mirguest — APPROVED** [review]
Looks good.

**Pull request merged**
