### PR TITLE
Add Clupatra Tracking algorithm 

### PR DESCRIPTION
**Pull request by zhaomr13**
The first version to add Clupatra tracking algorithm.
Correct the TrackerHit*  -> ConstTrackerHit.
In the future, this data type incorrect usage should also be reviewed.

### CODE REVIEW

**Comment by mirguest** [comment]
Hi Mingrui,

Thanks for your work. I think it's better to separate your WP into two parts:
* Adding Clupatra algorithm
* Correct the data type

Have you discuss with @fucd about the correction of data type?

Tao

**Comment by fucd** [comment]
Hi @zhaomr13 @mirguest 

I also agree change TrackerHit to ConstTrackerHit, but from ConstTrackerHit* to ConstTrackerHit, I am not clear how much the memory and CPU time will change, if thousands hits. Do you have clear estimation? If not, let us do a test?

Chengdong

**Comment by zhaomr13** [comment]
Hi @fucd @mirguest ,
Of course we should do a test. And I agree to make 
+ Adding Clupatra algorithm
+ Correct the data type
into two steps.

For the thing that Chengdong concerning, if you look at the source code of  plcio: http://cepcgit.ihep.ac.cn/cepc-prototype/plcio/-/blob/CEPC/source/datamodel/src/TrackerHit.cc (And I think the podio should be the same). Inside the TrackerHit/ConstTrackerHit type, there is a data member of TrackerHitObj, who contains the real data. When assigning a trackerHit to another trackerHit, it will only assign the reference of the trackerhit object(l.53 - l.40). So that we do not need to worry about the large time costing and we do not need to use TrackerHit*.

**Comment by zhaomr13** [comment]
I close a merge request and to split it into two steps.

**Pull request closed without merging**
