### PR TITLE
Add initial commit of Clupatra

### PR DESCRIPTION
**Pull request by zhaomr13**
The Clupatra code is test to generate the same results as the Marlin.
There are still two issues.

+ Uses global variables that pollutes the project.
+ Have memory leak. 

Despite having these issues we prefer to merge these workable codes to the master and fix the issues later.

### CODE REVIEW

**Comment by mirguest** [comment]
Hi @fucd ,
Could you help us review Mingrui's PR? 
Thanks!
Tao

**Comment by mirguest** [comment]
Hi @zhaomr13 ,
To remind us the existing issues, could you just create a new issue to describe the problems?
Tao

**Comment by fucd** [comment]
Hi @zhaomr13 @mirguest 

Sure, I have take a quick review on this pull request. I have comments on TrackingHelper. This can be regarded as a common class besides clupatra. Currently, the common helper classes are put in DataHelper, and it will be re-organized as following the code rules in future. Can it be also put into DataHelper in advance beforehand?

And in TrackingHelper class, the `getTrackStateAt` seems not return right values?
`inline edm4hep::TrackState getTrackStateAt(edm4hep::ConstTrack track, int location) {
    for (auto it = track.trackStates_begin(); it != track.trackStates_end(); it++) {
        if (it->location == location) {
            *it;
        }
    }
    return edm4hep::TrackState();
}` 

Best,
Chengdong

**Review by fucd — COMMENTED** [review]
Hi @zhaomr13

Thanks your update.

Hi @mirguest 

It is strange that travis-ci seems not work. I have also test compile ok. Some code rules work can be considered in next step. Can you merge it into master?

Best
Chengdong

**Review by fucd — APPROVED** [review]

**Review by fucd — APPROVED** [review]

**Comment by fucd** [comment]
Hi @mirguest 

With merging #52 , it can not pass `cmake` now, although ii can be compiled on standalone. It is strange.  The algorithm depends on TrackSystemSvc, and TrackSystemSvc depends on KalDet, and KalDet depends on DD4hep. But now, if not add `find_package(DD4hep COMPONENTS DDCore DDRec REQUIRED)` into [Reconstruction/Tracking/CMakeLists.txt](Reconstruction/Tracking/CMakeLists.txt) , cmake will report DD4hep::DDCore/DD4hep::DDRec not found. This issue also happened in SiliconTracking and TrackSystemSvc. I don't know why need to require indirect dependencies. Does it nonstandard cmake usage exist? Do you have any idea? 

Best,
Chengdong

**Review by mirguest — APPROVED** [review]

**Pull request merged**
