### PR TITLE
update CEPCv4 ECAL and HCAL xml

### PR DESCRIPTION
**Pull request by wenxingfang**
The cell offset of SEcal05_siw_Endcaps， SEcal05_siw_ECRing_01， and HcalRpc01_Barrel_01 are set in order to keep the cell position to be same with  Mokka's.

### CODE REVIEW

**Comment by wenxingfang** [comment]
@fucd @mirguest 
Could you give this PR a review? Thanks!

Best,
Wenxing

**Comment by fucd** [comment]
Hi @wenxingfang 
Thank you to update them. I have some comments.
In fact, the offset should be set as the edge of the sensitive shape. For ECRing, its size is
 `double ECRingSiplateSize = Ecal_endcap_center_box_size - 2 * Ecal_EC_Ring_gap - 2 * Ecal_lateral_face_thickness`, so the offset should be -0.5*ECRingSiplateSize. If set like this, besides the hit center, the hit id will become same as Mokka's. By your modification, although the centers are almost same, but id are still different. Simlar for EcalEndcaps, can you update them?

Chengdong

**Comment by wenxingfang** [comment]
Hi @fucd ，

Thank you for your suggestion, but I am not familiar what you said. How about you update the xml files accroding to my offset values you saw, and I will check you updates ?

Best,
Wenxing

**Comment by fucd** [comment]
@wenxingfang 
sure, I can update them. But for Hcal, construction file should be updated too, because sizes of its segmentations are vary. I will modify in next commit.

Best,
Chengdong

**Comment by wenxingfang** [comment]
@fucd 
Thanks. For HCAL, what do you mean its segmentations are varied? Do you find some bugs?

Best,
Wenxing

**Comment by fucd** [comment]
@wenxingfang 
I pushed a commit into your PR, can you merge it?

Chengdong

**Comment by fucd** [comment]
Hi @mirguest 
Wengxing and I have make CEPCv4 description more close to Mokka's. More improve will be continued to do, but as an important step, I think it can be merged at first now. Can you take last review and then merge it into CEPCSW?

Chengdong

**Review by mirguest — APPROVED** [review]
Looks good. Thanks.

**Pull request merged**
