### PR TITLE
SIM: Birks option to apply energy correction for scintillator

### PR DESCRIPTION
**Pull request by fucd**
* optional correction for birks coefficient, example in python job option
  * `from Configurables import CalorimeterSensDetTool`
  * `cal_sensdettool = CalorimeterSensDetTool("CalorimeterSensDetTool")`
  * `cal_sensdettool.CalNamesApplyBirks = ["EcalBarrel"]`

### CODE REVIEW

**Comment by fucd** [comment]
@qwert2333 Hi Fangyi, this PR add Birks law correction for scintillator. Now I set default to apply Birks law. If not apply is expected, please let me know. And please have a review. This PR has update on some same files in PR  #212 .

**Comment by fucd** [comment]
@mirguest Hi Tao, how about set for type of calorimeter? Please give some suggestions or comments.

**Comment by mirguest** [comment]
Hi @fucd,
In my opinion, the type "scintillator" may be not very clear. How about specify the names explictly in SDTool, such as `m_listCalsApplyBirks` ?
BTW: in the JUNO experiment, we actually store two energies: deposit energy (before) and visible energy (after). 
Tao

**Comment by fucd** [comment]
@mirguest Thank you, you are right. My consider is to reduce control positions for users, and then we can tell them "this to change" not "these to change". Best is DD4hep's interface like "combineHits", but has not. So maybe we can only have a un-perfect method. I will change. For energy storage, currently, the two energies are transmitted to next. Hit's energy is after, and energy in truth contrib is before. If needed, we can save them in step from G4 hits to EDM4hep hits.
BTW: my suggestion is to change m_listCalsMergeDisable to  "combineHits" option in compact files, how about it? 

> Hi @fucd, In my opinion, the type "scintillator" may be not very clear. How about specify the names explictly in SDTool, such as `m_listCalsApplyBirks` ? BTW: in the JUNO experiment, we actually store two energies: deposit energy (before) and visible energy (after). Tao

**Comment by fucd** [comment]
@mirguest I changed sensitive type back. Have you any more comments?

**Review by mirguest — APPROVED** [review]
Looks good for me. Thank you @fucd .

**Pull request merged**
