### PR TITLE
SIM: implement CEPCv4 Hcal geometry

### PR DESCRIPTION
**Pull request by fucd**
* construction
    * [SHcalRpc01_Barrel.cpp](Detector/DetCEPCv4/src/calorimeter/SHcalRpc01_Barrel.cpp)
    * [SHcalRpc01_Endcaps.cpp](Detector/DetCEPCv4/src/calorimeter/SHcalRpc01_Endcaps.cpp)
    * [SHcalRpc01_EndcapRing.cpp](Detector/DetCEPCv4/src/calorimeter/SHcalRpc01_EndcapRing.cpp)
* compact
    * [SHcalRpc01_Barrel_01.xml](Detector/DetCEPCv4/compact/SHcalRpc01_Barrel_01.xml)
    * [SHcalRpc01_Endcaps_01.xml](Detector/DetCEPCv4/compact/SHcalRpc01_Endcaps_01.xml)
    * [SHcalRpc01_EndcapRing_01.xml](Detector/DetCEPCv4/compact/SHcalRpc01_EndcapRing_01.xml)
    * fix difference of Hcal parameters with CEPCv4
    * add material RPC2ECRMix for Endcaps and EndcapRing, same slice structure with Barrel  is also supported, currently keep same as MokkaC
* display
    * overview
    * XZview

### CODE REVIEW

**Comment by fucd** [comment]
@mirguest Travis CI does not work again? I watched PR #104  did not start building too.

**Comment by mirguest** [comment]
> @mirguest Travis CI does not work again? I watched PR #104 did not start building too.

Hi @fucd , Thank you to point the problem. 

It is due to the negative credit balance in the Travis CI. 
I will try other solutions.

Tao

**Comment by fucd** [comment]
@mirguest ok, thank you. And Hcal needs names of its collections, in preliminary, I name them as HcalBarrelCollection, HcalEndcapsCollection and HcalEndcapRingCollection like as Ecal, are them appropriate?

@wenxingfang @LinghuiWuIHEP Can you help to review it together with Tao?

**Comment by mirguest** [comment]
Hi @fucd ,
I have switched from Travis-CI to a self-hosted Github runners. Could you merge the master and push the changes to your pull request? Let's check whether it will work or not. Thank you.
Tao

**Comment by fucd** [comment]
@mirguest Sure, I have update the PR, and see build "In progress". SO seems it work! Great!

**Review by mirguest — APPROVED** [review]
Looks good. Thank you!

**Pull request merged**
