### PR TITLE
JOB: import python joboption for CRD

### PR DESCRIPTION
**Pull request by fucd**
* rename sim_CRD.py to CRD-Sim.py and move K4DataSvc to k4DataSvc
* add CRD_o1_v01-SimRec.py and CRD_o1_v02-SimRec.py
  * only silicon tracking, more reconstrutions, DC tracking, PFA, etc. to update

### CODE REVIEW

**Comment by fucd** [comment]
Hi @mirguest 

I import some job options for CRD simulation and reconstruction,  can you take a review?

Chengdong

**Comment by mirguest** [comment]
Hi @fucd ,
Thanks for this PR. Just one comment: the random number seed should be set as following in the latest software:
* https://github.com/cepc/CEPCSW/blob/master/Examples/options/tut_detsim.py
Especially the seed should be also set in the DetSimAlg:
```python
detsimalg.RandomSeeds = seed
```

**Review by mirguest — APPROVED** [review]
Thanks @fucd ! It looks good for me. 
Tao

**Comment by fucd** [comment]
@mirguest Thank you！

**Pull request merged**
