### PR TITLE
Support pandora to get CEPCv4 tracker geometry info from dd4hep

### PR DESCRIPTION
**Pull request by wenxingfang**
Support pandora to get CEPCv4 tracker geometry info from dd4hep.

### CODE REVIEW

**Comment by wenxingfang** [comment]
Hi @mirguest ,

Can you help me to review the changes and merge the pull request? Thanks!

Best,
Wenxing

**Comment by mirguest** [comment]
Hi @wenxingfang ,
You are using try catch in your code. But it would be better to catch the expected exceptions than just catch all. 
Tao

**Comment by wenxingfang** [comment]
Hi @mirguest ,
Thanks for you comments, I have updated the pull request, please check it. 
Best,
Wenxing

**Review by mirguest — APPROVED** [review]
Looks good. Thanks.
Tao

**Pull request merged**
