### PR TITLE
WIP: migrating TotalInvMass from Marlin to Gaudi.

### PR DESCRIPTION
**Pull request by mirguest**
- [x] A job option
- [x] Framework: Marlin to Gaudi
- [x] Event Data Model: LCIO to EDM4hep
- [ ] Get Event Header
- [ ] Decoder to get layer number
- [ ] Deploy the dependencies
  - [x] k4LCIOReader
  - [ ] k4LCIOInput
- [ ] Validation (Dan)

### CODE REVIEW

**Comment by mirguest** [comment]
Hi @danerdaner, 
Please review and test this PR. Thank you!
Tao

**Comment by mirguest** [comment]
Hi @zhaomr13 ,
This is an example of physics analysis algorithm. Could you also review and test it?
Tao

**Comment by zhaomr13** [comment]
Ok I will test it asap.

**Comment by mirguest** [comment]
> Ok I will test it asap.

Thank you @zhaomr13 
Tao

**Comment by mirguest** [comment]
The LCIOInput and k4LCIOReader are merged. The new package v0.2.0 is deployed at CVMFS: /cvmfs/cepcsw.ihep.ac.cn/prototype/releases/externals/97.0.2/k4LCIOReader

**Pull request merged**
