### PR TITLE
WIP: updating DCHDigi

### PR DESCRIPTION
**Pull request by wenxingfang**
WIP: updating DCHDigi

### CODE REVIEW

**Comment by mirguest** [comment]
Hi @wenxingfang,
Please update the description. You should describe the details.
Thanks.
Tao

**Comment by wenxingfang** [comment]
update : using closest sim hit position as trackerHit position. Most parts are finished, only waiting for getting signal wire position by cell id using dd4hep.

**Review by mirguest — COMMENTED** [review]
Do you really need to use Geant4?

**Comment by wenxingfang** [comment]
Ok, I will use TVector3 to replace G4ThreeVector, then G4 is not needed.

**Comment by wenxingfang** [comment]
or I can use DDRec/Vector3D.h

**Comment by wenxingfang** [comment]
@mirguest I want merge this pull request for now, because only missing part is to get the geo info for DCH cell, which can be slove by creating another issue.

**Review by mirguest — APPROVED** [review]

**Pull request merged**
