### PR TITLE
update ClupatraAlg and fix its runtime error

### PR DESCRIPTION
**Pull request by fucd**
* update track system interface according to #68 and apply filter option input from python
* add Segments output
    * issue: if not add, Track link will meet crash?
    * change `ConstTrack` to `Track`,  because only `Track` class can call `addToTracks(...)`
* TrackingHelper.h
    * move to [Reconstruction/Tracking/Tracking](Reconstruction/Tracking/Tracking) , since FullLDCTrackingAlg will also use it
* clupatra_new::operator()
    * issue: sometime while applying ClupatraAlg on CEPCSW simulated and TPCDigiAlg digitized data, cannot get available TrackerHit object while `mtrk->getTrackerHitAtPositiveNDF( last_constrained_hit );`
    * add protection and TODO: check how this problem causes

### CODE REVIEW

**Comment by fucd** [comment]
Hi @zhaomr13 

Could you help me to review it and #71 ?

Chengdong

**Comment by mirguest** [comment]
Hi @fucd ,
So this PR is related to the reconstruction. Could make your title more clear? Thanks.

Hi @zhaomr13 and @ihepzhangyao , could you help Chengdong review his code? Thank you.

Tao

**Comment by fucd** [comment]
Hi @mirguest 

Sure, I modified it. Thanks very much!

**Comment by zhaomr13** [comment]
Hi @mirguest ,
I think it is ok to merge this pull request. 
And I created issue #72 for the remaining bug.

**Comment by mirguest** [comment]
Hi @fucd and @zhaomr13 ,
I found there are some variables with `Plcio`, such as `ClupaPlcioTrack`. Do you need to rename them?
Thanks.
Tao

**Comment by zhaomr13** [comment]
> Hi @fucd and @zhaomr13 ,
> I found there are some variables with `Plcio`, such as `ClupaPlcioTrack`. Do you need to rename them?
> Thanks.
> Tao

@mirguest Not necessary to change it now. We can think a better, maybe data model independent name in the future.

**Pull request merged**
